(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'987dbb04-0c19-471a-9a10-cfe220e1c1ad-bootstrap-container',
          componentName:'BlogRouter3',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"visitorMode":true,"currentPageRoute":"\u002Fblog","preset":"rss3","order":0,"id":"987dbb04-0c19-471a-9a10-cfe220e1c1ad","viewDevice":null,"env":"production","websiteId":"556796cb-503b-4fcc-8fbe-a9aa56c2d232","appDomain":"godaddy.com","isReseller":false,"staticContent":{"edit_mode_cta":{"title":"You don't have any blog posts yet","sub_title":"Let's create some content","btn_label":"Start Writing"},"readMore":"Continue Reading","staticFeed":[{"title":"Everything in its Place","content":"The French phrase “Mis En Place” is taught to culinary students from the moment they enter school. Having “everything in its place” makes all the difference when the pressure is on and orders are piling up."},{"title":"Cold and Sweet Chocolate Treat","content":"Every now and then the craving hits for something cold, creamy, and loaded with chocolate goodness. Here is a quick and easy recipe to satisfy your chocolate needs!"},{"title":"Picnic Lunch","content":"Taking food on the go can be a challenge. The same old sandwiches can get boring. Here are some lunch ideas to keep your picnics exciting."},{"title":"The Perfect Poached Egg","content":"There’s nothing more delicious in the morning than a perfectly poached egg. Honing your technique will make you the star of your friendly brunch gatherings."},{"title":"Picnic Lunch","content":"A box of random assorted vegetables is full of delicious possibilities. However, when your box arrives from your favorite farm, what do you do with all of this fresh produce?"}],"socialSharing":{"sharePost":"Share this post"},"rssToEmail":{"signUp":"Sign up","placeholder":"Email address","confirmation_1":"Thanks for signing up!","confirmation_2":"We'll send blog updates and other company news directly to your inbox.","confirmation_3":"Check your email to confirm your subscription.","cta":"Sign up for blog updates!","cta_subhed":"Join my email list to receive updates and information."},"noPosts":"Posts coming soon!","allPosts":"All Posts","recentPosts":"Recent Posts","categories":"Categories","feedNotFetchable":"Sorry, we couldn't find your blog feed. Please check your URL and try again."},"pageId":"32ee2d0e-a71d-4c56-8386-38fb04c5b4c9","sectionTitle":"My Blog","blogType":"internal","rssFeed":"http:\u002F\u002Ffoodnetwork.tumblr.com\u002Frss","categoriesFilter":[],"layoutNum":3,"widgetId":"987dbb04-0c19-471a-9a10-cfe220e1c1ad","section":"default","category":"neutral","locale":"en-IN","renderMode":"PUBLISH"},{"widgetId":"987dbb04-0c19-471a-9a10-cfe220e1c1ad","widgetType":"RSS","widgetPreset":"rss3","section":"default","category":"neutral","fontSize":"medium","fontFamily":"alternate","group":"Section","groupType":"Default"});